config/routes.rb
Rails.application.routes.draw do
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :services,only: [:index, :new, :create, :show, :edit, :update]
    resources :customers,only: [:index, :edit, :show, :update]
    resources :requests,only: [:show, :update]
    resources :request_details,only: [:update]
    resources :questions,only: [:index, :edit, :show, :update]
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 顧客側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :services,only: [:index, :show]
    resources :request_lists, only: [:index, :create, :destroy, :update] do
      collection do
        delete 'destroy_all'
      end
    end
    get 'customers/my_page' => 'customers#show'
    get 'customers/my_page/edit' => 'customers#edit'
    patch 'customers/my_page' => 'customers#update'
    get 'customers/my_page/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/my_page/withdraw' => 'customers#withdraw'
    resources :requests,only: [:index, :create, :new, :show, :update] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    resources :questions,only: [:create, :new, :index, :show] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
  has_many :request_lists, dependent: :destroy
  has_many :request_details, dependent: :destroy

  validates :image, presence: true
  validates :service_name, presence: true
  validates :service_introduction, presence: true
  validates :price, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  # 税込価格を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @service = Service.where("service_name LIKE?", "#{word}")
    elsif search == "partial_match"
      @service = Service.where("service_name LIKE?","%#{word}%")
    else
      @service = Service.all
    end
  end

# 絞り込み機能
  def self.sorts(search, word)
    if search == "id"
      @service = Service.where("id LIKE?", "%#{word}%")
    elsif search == "name"
      @service = Service.where("service_name LIKE?","%#{word}%")
    elsif search == "price"
      @service = Service.where("price LIKE?","%#{word}%")
    else
      @service = Service.all
    end
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
  def index
    @services = Service.sorts(params[:search], params[:word])
    # @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    service = Service.new(service_params)
    if service.save
      flash[:notice] = "登録に成功しました。"
      redirect_to admin_service_path(service)
    else
      flash[:alert] = "登録に失敗しました。"
      render :new
    end
  end

  def show
    @service = Service.find(params[:id])
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      flash[:notice] = "更新に成功しました。"
      redirect_to admin_service_path(@service)
    else
      flash[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  private

  def service_params
    params.require(:service).permit(:image, :service_name, :service_introduction, :price, :is_active)
  end
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/views/admin/services/edit.html.erb
<div class="container">
  <h2 class="font-weight-bold">サービス編集</h2>
  <%= form_with model: @service, url: admin_service_path(@service) do |f| %>
  <div class="d-flex justify-content-center m-4">
    <div class="row bg-white text-border pt-3 px-3">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>画像</th>
            <td><%= f.file_field :image, accept: "image/*"  %></td>
          </tr>
          <tr>
            <th>サービス名</th>
            <td><%= f.text_field :service_name, size: 35 %></td>
          </tr>
          <tr>
            <th>サービス説明</th>
            <td><%= f.text_area :service_introduction, size: "38x5" %></td>
            </tr>
          <tr>
            <th>税抜価格</th>
            <td><%= f.text_field :price, size: 35 %></td>
          </tr>
          <tr>
            <th>提供ステータス</th>
            <th>
              <%= f.radio_button :is_active, false %><%= f.label :is_active, "利用可能" %>
              <%= f.radio_button :is_active, true %><%= f.label :is_active, "利用停止" %>
            </th>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center m-1">
    <%= f.submit "変更を保存", class:"btn btn-success m-2 px-4 py-2" %>
  </div>
  <% end %>
</div>

app/views/admin/services/index.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col text-left">
      <h2 class="font-weight-bold">サービス一覧</h2>
    </div>
    <div class="search_form">
      <%= form_with url: admin_services_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %>
        <%= f.select :search, options_for_select([["サービスID","id"], ["サービス名","name"], ["税抜価格","price"]]) %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col text-right">
      <%= link_to "新規登録",new_admin_service_path, class: "btn btn-success" %>
    </div>
  </div>
  <% if @services.any? %>
  <div class="row mx-1">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>サービスID</th>
          <th>サービス名</th>
          <th>税抜価格</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @services.each do |service| %>
        <tr>
          <td><%= service.id %></td>
          <td><%= link_to service.service_name, admin_service_path(service.id) %></td>
          <td><%= number_with_delimiter(service.price, delimiter: ',') %></td>
          <td>
            <% if service.is_active %>
              <p class="text-secondary font-weight-bold">利用停止</p>
            <% else %>
              <p class="text-success font-weight-bold">利用可能</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% else %>
  <div class="row mt-4">
    <div class="pl-3">
      <p>該当のデータがありませんでした</p>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/services/new.html.erb
<div class="container">
  <h2 class="font-weight-bold ml-5">サービス新規登録</h2>
  <%= form_with model: @service, url: admin_services_path, method: :post do |f| %>
  <div class="d-flex justify-content-center m-4">
    <div class="row bg-white text-border pt-3 px-3">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td>画像</td>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <td>サービス名</td>
          <td><%= f.text_field :service_name, placeholder:"サービス名", size: 35 %></td>
        </tr>
        <tr>
          <td>サービス説明</td>
          <td><%= f.text_area :service_introduction, placeholder:"ここに説明文を記述します", size: "38x5" %></td>
        </tr>
        <tr>
          <td>税抜価格</td>
          <td><%= f.text_field :price, placeholder:"1000", size: 35 %>　円</td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
  <div class="d-flex justify-content-center m-1">
    <%= f.submit '新規登録', class:"btn btn-success m-2 px-4 py-2" %>
  </div>
  <% end %>
</div>

app/views/admin/services/show.html.erb
<div class="container">
  <h2 class="font-weight-bold">サービス詳細</h2>
  <div class="row m-3">
    <div class="col-6 ml-auto">
      <%= image_tag @service.get_image(400,400), class:"bg-white text-border p-3" %>
    </div>
    <div class="col-6 mr-auto">
      <div class="row bg-white text-border p-2">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th style="width: 30%"></th>
              <td style="width: 70%"></td>
            </tr>
            <tr>
              <th>サービス名</th>
              <td><%= @service.service_name %></td>
            </tr>
            <tr>
              <th>サービス説明</th>
              <td><%= @service.service_introduction %></td>
            </tr>
            <tr>
              <th>提供価格(税抜)</th>
              <td>
                <%= number_with_delimiter(@service.with_tax_price.floor, delimiter: ',') %>
                (<%= number_with_delimiter(@service.price, delimiter: ',') %>) 円
              </td>
            </tr>
            <tr>
              <th>提供ステータス</th>
              <td>
                <% if @service.is_active %>
                  <p class="text-secondary font-weight-bold">利用停止</p>
                <% else %>
                  <p class="text-success font-weight-bold">利用可能</p>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="d-flex justify-content-center">
        <%= link_to "編集する",edit_admin_service_path, class:"btn btn-success m-3 py-2 px-4" %>
      </div>
    </div>
  </div>

</div>