config/routes.rb
Rails.application.routes.draw do
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :services,only: [:index, :new, :create, :show, :edit, :update]
    resources :customers,only: [:index, :edit, :show, :update]
    resources :requests,only: [:show, :update]
    resources :request_details,only: [:update]
    resources :questions,only: [:index, :edit, :show, :update]
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 顧客側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :services,only: [:index, :show]
    resources :request_lists, only: [:index, :create, :destroy, :update] do
      collection do
        delete 'destroy_all'
      end
    end
    get 'customers/my_page' => 'customers#show'
    get 'customers/my_page/edit' => 'customers#edit'
    patch 'customers/my_page' => 'customers#update'
    get 'customers/my_page/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/my_page/withdraw' => 'customers#withdraw'
    resources :requests,only: [:index, :create, :new, :show, :update] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    resources :questions,only: [:create, :new, :index, :show] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "Customer"
      @customers = Customer.looks(params[:search], params[:word])
      @title = "会員一覧"
      @count = @customers.count
    elsif @range == "Question"
      @questions = Question.looks(params[:search], params[:word])
      @title = "お問い合わせ一覧"
      @count = @questions.count
    elsif @range == "Request"
      @requests = Request.looks(params[:search], params[:word])
      @title = "依頼履歴一覧"
      @count = @requests.count
    elsif @range == "Service"
      @services = Service.looks(params[:search], params[:word])
      @title = "サービス一覧"
      @count = @services.count
    else
      redirect_to admin_root_path
    end
    render "/admin/searches/search_result"
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_search.html.erb
<% if admin_signed_in? %>
  <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, class:"form-control mr-1", placeholder:"検索", type: "search" %>
    <%= f.select :range, options_for_select([["会員名(姓or名)",'Customer'], ["お問い合わせ名",'Question'], ["依頼者名",'Request'], ["サービス名",'Service']]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-primary mt-1" %>
  <% end %>
<% end %>

app/views/admin/searches/search_result.html.erb
<div class="container">
  <h2 class="font-weight-bold"><%= @title %></h2>
  <div class="row m-3">
  <h4>"<%= @word %>"の検索結果(全<%= @count %>件)</h4>
  <table class="table table-hover table-inverse">
  <% if @range == "Customer" %><!--検索対象モデルがCustomerの時 -->
    <% if @customers.any? %>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to "#{customer.last_name}#{customer.first_name}", admin_customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_deleted %>
            <p class="text-secondary font-weight-bold">退会</p>
          <% else %>
            <p class="text-success font-weight-bold">有効</p>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <% else %><!-- @customers が nil の場合の処理 -->
    </table>
    <div class="row m-3">
      <p>データが見つかりませんでした</p>
    </div>
    <% end %>
  <% elsif @range == "Question" %><!--検索対象モデルがQuestionの時-->
    <% if @questions.any? %>
    <thead>
      <tr>
        <th>問い合わせID</th>
        <th>問い合わせ名</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= link_to question.questions_name, admin_question_path(question.id) %></td>
        <td>
          <% if question.is_answer %>
            <p class="text-secondary font-weight-bold">回答済み</p>
          <% else %>
            <p class="text-success font-weight-bold">未回答</p>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <% else %><!-- @customers が nil の場合の処理 -->
    </table>
    <div class="row m-3">
      <p>データが見つかりませんでした</p>
    </div>
    <% end %>
  <% elsif @range == "Request" %><!--検索対象モデルがRequestの時-->
    <% if @requests.any? %>
    <thead>
      <tr>
        <th>申請日時</th>
        <th>依頼者</th>
        <th>利用冊数</th>
        <th>申し込みステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @requests.each do |request| %>
      <tr>
        <th><%= link_to request.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_request_path(request.id) %></th>
        <th><%= request.address_name %></td>
          <% total = 0 %>
          <% request.request_details.each do |request_detail| %>
            <% total += request_detail.amount %>
          <% end %>
        <td><%= total %></td>
        <th><%= request.requests_status_i18n %></th>
      </tr>
      <% end %>
    </tbody>
    <% else %><!-- @customers が nil の場合の処理 -->
    </table>
    <div class="row m-3">
      <p>データが見つかりませんでした</p>
    </div>
    <% end %>
  <% elsif @range == "Service" %><!--検索対象モデルがServiceの時-->
    <% if @services.any? %>
    <thead>
      <tr>
        <th>サービスID</th>
        <th>サービス名</th>
        <th>税抜価格</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.id %></td>
          <td><%= link_to service.service_name, admin_service_path(service.id) %></td>
          <td><%= number_with_delimiter(service.price, delimiter: ',') %></td>
          <td>
            <% if service.is_active %>
              <p class="text-secondary font-weight-bold">利用停止</p>
            <% else %>
              <p class="text-success font-weight-bold">利用可能</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <% else %><!-- @customers が nil の場合の処理 -->
    </table>
    <div class="row m-3">
      <p>データが見つかりませんでした</p>
    </div>
    <% end %>
  <% end %>
  </table>
</div>