config/routes.rb
Rails.application.routes.draw do
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :services,only: [:index, :new, :create, :show, :edit, :update]
    resources :customers,only: [:index, :edit, :show, :update]
    resources :requests,only: [:show, :update]
    resources :request_details,only: [:update]
    resources :questions,only: [:index, :edit, :show, :update]
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 顧客側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :services,only: [:index, :show]
    resources :request_lists, only: [:index, :create, :destroy, :update] do
      collection do
        delete 'destroy_all'
      end
    end
    get 'customers/my_page' => 'customers#show'
    get 'customers/my_page/edit' => 'customers#edit'
    patch 'customers/my_page' => 'customers#update'
    get 'customers/my_page/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/my_page/withdraw' => 'customers#withdraw'
    resources :requests,only: [:index, :create, :new, :show, :update] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    resources :questions,only: [:create, :new, :index, :show] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :customer
  has_many :request_details, dependent: :destroy

  enum pay_method: { credit_card: 0, transfer: 1 }
  enum requests_status: { waiting: 0, confirmation: 1, processing: 2, in_use: 3, cancel: 4 }

  validates :pay_method, presence: true
  validates :postage, presence: true
  validates :pay_money, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :address_name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + address_name
  end

  def address_no_name
  '〒' + postal_code + ' ' + address
  end

  def total
    pay_money - postage
  end

# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @request = Request.where("address_name LIKE?", "#{word}")
    elsif search == "partial_match"
      @request = Request.where("address_name LIKE?","%#{word}%")
    else
      @request = Request.all
    end
  end

# 絞り込み機能
  def self.sorts(search, word)
    if search == "created_at"
      @request = Request.where("created_at LIKE?", "%#{word}%")
    elsif search == "address_name"
      @request = Request.where("address_name LIKE?","%#{word}%")
    else
      @request = Request.all
    end
  end

end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  def show
    @request = Request.find(params[:id])
    @request_details = @request.request_details.all
  end

  def update
    # ↓更新予定の申し込みデータを取得↓
    request = Request.find(params[:id])
    # ↓紐づいた申し込み内容データを取得↓
    request_details = RequestDetail.where(request_id: params[:id])
    # ↓申し込みステータスを更新↓
    if request.update(request_params)
      if request.requests_status == "waiting" # 申し込みステータスが「入金待ち」だったら
        request_details.update(storage_status: 0, sale_status: 0, disposal_status: 0)
      elsif request.requests_status == "confirmation" # 申し込みステータスが「入金確認」だったら
        request_details.update(storage_status: 1, sale_status: 1, disposal_status: 1)
      elsif request.requests_status == "in_use" # 申し込みステータスが「サービス利用中」だったら
        request_details.update(storage_status: 2, sale_status: 2, disposal_status: 2)
      elsif request.requests_status == "cancel" # 申し込みステータスが「キャンセル」だったら
        request_details.update(storage_status: 3, sale_status: 3, disposal_status: 3)
      else
        flash[:alert] = "ステータスの更新に失敗しました。"
      end
      flash[:alert] = "ステータスを更新しました。"
    else
      flash[:alert] = "情報の更新に失敗しました。"
    end
    redirect_to  admin_request_path(request)
  end

  private

  def request_params
    params.require(:request).permit(:requests_status)
  end
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/views/admin/requests/show.html.erb
<div class="container">
  <h2 class="font-weight-bold">依頼履歴詳細</h2>
  <div class="row mt-4 pt-3 px-3 bg-white text-border">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th>依頼者</th>
          <th><%= link_to @request.address_name, admin_customer_path(@request.customer_id) %></th>
        </tr>
        <tr>
          <th>注文日</th>
          <th><%= @request.created_at.strftime('%Y/%m/%d') %></th>
        </tr>
        <tr>
          <th>配送先</th>
          <th><%= @request.address_no_name %></th>
        </tr>
        <tr>
          <th>支払方法</th>
          <th><%= @request.pay_method_i18n %></th>
        </tr>
        <tr>
          <th>申し込みステータス</th>
          <th>
            <%= form_with model: @request, url: admin_request_path(@request) do |f| %>
              <%= f.select :requests_status, Request.requests_statuses.keys.map { |k| [I18n.t("enums.request.requests_status.#{k}"), k] } %>
              <%= f.submit "更新", class:"btn btn-sm btn-success", method: :patch %>
            <% end %></th>
        </tr>
  <!---------------------------------------------------------------------------------------------->
  <!--各ステータスを更新する申し込みステータスのみ表示させたい場合(将来対応)-->
  <!--コメントアウト(<% if false %><% end %>)を外す-->

  <% if false %>
        <% if @request.requests_status == "waiting" %>
        <tr>
          <th>ステータスの更新</th>
          <th>
            <%= form_with model: @request, url: admin_request_path(@request) do |f| %>
              <%= f.select :requests_status, Request.requests_statuses.slice(:confirmation, :cancel).keys.map { |k| [I18n.t("enums.request.requests_status.#{k}"), k] } %>
              <%= f.submit "更新", class:"btn btn-sm btn-success", method: :patch %>
            <% end %>
          </th>
        </tr>
        <% else %>
        <tr>
          <th>ステータスの更新</th>
          <th>
            <%= form_with model: @request, url: admin_request_path(@request) do |f| %>
              <%= f.select :requests_status, Request.requests_statuses.slice(:cancel).keys.map { |k| [I18n.t("enums.request.requests_status.#{k}"), k] } %>
              <%= f.submit "更新", class:"btn btn-sm btn-success", method: :patch %>
            <% end %>
          </th>
        </tr>
        <% end %>
  <% end %>
  <!---------------------------------------------------------------------------------------------->
      </tbody>
    </table>
  </div>
  <div class="row my-3">
    <div class="col-7 m-auto bg-white text-border">
      <table class="table">
        <thead>
          <tr>
            <th class="text-center">サービス名</th>
            <th class="text-center">利用冊数</th>
            <th class="text-center">単価(税込)</th>
            <th class="text-center" colspan="2">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @request_details.each do |request_detail| %>
          <tr>
            <td class="text-center"><%= request_detail.service.service_name %></td>
            <td class="text-center"><%= request_detail.amount %></td>
            <td class="text-center"><%= number_with_delimiter(request_detail.service.with_tax_price, delimiter: ',') %></td>
            <td class="text-center">
              <%= form_with model: request_detail, url: admin_request_detail_path(request_detail.id) do |f| %>
                <%= f.hidden_field :request_id, :value => request_detail.request_id %>
                <%= f.hidden_field :service_id, :value => request_detail.service_id %>
              <% if request_detail.service.id == 1 %>
                <%= f.select :storage_status, RequestDetail.storage_statuses.keys.map { |k| [I18n.t("enums.request_detail.storage_status.#{k}"), k] } %>
                <%= f.hidden_field :sale_status, :value => request_detail.sale_status %>
                <%= f.hidden_field :disposal_status, :value => request_detail.disposal_status %>
              <% elsif request_detail.service_id == 2 %>
                <%= f.select :sale_status, RequestDetail.sale_statuses.keys.map { |k| [I18n.t("enums.request_detail.sale_status.#{k}"), k] } %>
                <%= f.hidden_field :storage_status, :value => request_detail.storage_status %>
                <%= f.hidden_field :disposal_status, :value => request_detail.disposal_status %>
              <% elsif request_detail.service_id == 3 %>
                <%= f.select :disposal_status, RequestDetail.disposal_statuses.keys.map { |k| [I18n.t("enums.request_detail.disposal_status.#{k}"), k] } %>
                <%= f.hidden_field :storage_status, :value => request_detail.storage_status %>
                <%= f.hidden_field :sale_status, :value => request_detail.sale_status %>
              <% elsif %>
                <p>ステータスなし</p>
              <% end %>
            </td>
            <td class="text-center">
                <%= f.submit "更新", class:"btn btn-sm btn-success", method: :patch %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-2"></div>
    <div class="col-3 m-auto pt-3 px-4 bg-white text-border">
      <div class="row text-bottom">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th>商品合計</th>
              <td><%= number_with_delimiter(@request.total, delimiter: ',') %>円</td>
            </tr>
            <tr>
              <th>送料</th>
              <td><%= @request.postage %>円</td>
            </tr>
            <tr>
              <th>請求金額合計</th>
              <th><%= number_with_delimiter(@request.pay_money, delimiter: ',') %>円</th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div>
    <%= link_to "依頼履歴一覧へ戻る",admin_root_path, class:"btn btn-secondary" %>
  </div>
</div>