config/routes.rb
Rails.application.routes.draw do
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :services,only: [:index, :new, :create, :show, :edit, :update]
    resources :customers,only: [:index, :edit, :show, :update]
    resources :requests,only: [:show, :update]
    resources :request_details,only: [:update]
    resources :questions,only: [:index, :edit, :show, :update]
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 顧客側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :services,only: [:index, :show]
    resources :request_lists, only: [:index, :create, :destroy, :update] do
      collection do
        delete 'destroy_all'
      end
    end
    get 'customers/my_page' => 'customers#show'
    get 'customers/my_page/edit' => 'customers#edit'
    patch 'customers/my_page' => 'customers#update'
    get 'customers/my_page/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/my_page/withdraw' => 'customers#withdraw'
    resources :requests,only: [:index, :create, :new, :show, :update] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    resources :questions,only: [:create, :new, :index, :show] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    get "search" => "searches#search"
    # get "search_result" => "searches#search_result"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SBSSサイト</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/77a69e9882.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
  <!--ヘッダー開始-->
    <header class="bg-light shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand sbss-border" href="/">
            <%= image_tag "SBSS - MarkMaker Logo.jpg", size: '100x35' %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <div class="search_form mx-2" id="navbarNavDropdown">
                <%= render 'public/searches/search' %>
                <%= render 'admin/searches/search' %>
              </div>
              <div class="btn-wrapper">
              <% if customer_signed_in? %>
              <!--顧客ログイン済みの場合-->
                <%= link_to "マイページ",customers_my_page_path(current_customer), class:"btn btn-info mx-2" %>
                <%= link_to "サービス一覧",services_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "依頼予定リスト",request_lists_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "お問い合わせ",new_question_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "ログアウト",destroy_customer_session_path, class:"btn btn-danger mx-2", method: :delete %>
              <% elsif admin_signed_in? %>
              <!--管理者ログイン済みの場合-->
                <%= link_to "サービス一覧",admin_services_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "会員一覧",admin_customers_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "依頼履歴一覧",admin_root_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "お問い合わせ一覧",admin_questions_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "ログアウト",destroy_admin_session_path, class:"btn btn-danger mx-2", method: :delete %>
              <% else %>
                <!--ログインしていない場合-->
                <%= link_to "当サイトについて",about_path, class:"btn btn-info mx-2" %>
                <%= link_to "サービス一覧",services_path, class:"btn btn-secondary mx-2" %>
                <%= link_to "新規登録",new_customer_registration_path, class:"btn btn-primary mx-2" %>
                <%= link_to "ログイン",new_customer_session_path, class:"btn btn-success mx-2" %>
              <% end %>
              </div>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <!--ヘッダー終了-->

  <!--メイン開始-->
    <main>
      <div class="message-area text-top mb-3">
        <% flash.each do |message_type, message| %>
          <div class="flash-message <%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
    </main>
  <!--メイン終了-->

  <!--フッター開始-->
    <footer class="bg-dark text-white py-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-6">
            <p>あなたの不安を解消するサービスサイト</p>
          </div>
          <div class="col-md-6 pl-3">
            <h6 class="text-white mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="/homes/about" title="About" class="text-white-50">概要</a>
              </li>
              <li>
                <a href="/" title="Top" class="text-white-50">トップページ</a>
              </li>
              <li>
                <a href="/admins/sign_in" title="admin_sign_in" class="text-white-50">管理者ログイン</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  <!--フッター終了-->

  </body>

</html>